//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizEthic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BizImpactData
    {
        public string company_id { get; set; }
        public string company_name { get; set; }
        public Nullable<System.DateTime> date_first_certified { get; set; }
        public Nullable<System.DateTime> date_certified { get; set; }
        public string website { get; set; }
        public Nullable<double> overall_score { get; set; }
        public int IDCol { get; set; }
    }
}
